name: Build and deploy the lambda code using zip file

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Analysing the code with pre-commit hook
      run: |
        pre-commit run --all-files --verbose

  deploy-dev:
    runs-on: ubuntu-latest
    environment: "dev"
    needs: code-quality
    steps:
    - uses: actions/checkout@v3
    - name: Build Code
      run: |
        python --version
        sh +x build_zip_file.sh
        ls
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Push Zip file to S3
      run: |
        aws s3 cp retrive_s3_details.zip s3://lambda-processing-sai/buld_code/

    - name: Deploy to AWS Lambda by updating the zip file present in S3 bucket
      run: |
        aws lambda update-function-code \
              --function-name  retrive_s3_details \
              --s3-bucket lambda-processing-sai \
              --s3-key buld_code/retrive_s3_details.zip
