name: Build and deploy the lambda code using zip file

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Analysing the code with pre-commit hook
      run: |
        pre-commit run --all-files --verbose

  deploy-dev:
    runs-on: ubuntu-latest
    environment: "dev"
    needs: code-quality
    steps:
    - uses: actions/checkout@v3
    - name: Build Code
      run: |
        python --version
        sh +x build_zip_file.sh
        ls
